### ISSUE TITLE
[meta] Tidy up the UX and operation

### ISSUE THREAD

**Issue by lars-t-hansen** [knowit/snappysense#49]
This is a metabug pertaining to how the device operates and behaves.  Now that it all "works" it needs to work "well".  Some flexibility built into the firmware it probably needs to be removed.

Partly it is about #43: there probably needs to be a clean separation between monitoring and communication to avoid having wifi affect the temperature sensor (although #44 affects the needs for that, but I don't know whether #44 will happen). 

Partly this is about #30 and #38, the UX needs to be purposeful and smooth.

Partly this is about #33 and #3: it may take some time to make reliable measurements, and this larger "monitoring window" needs to be part of the design.

- [x] Allow for longer monitoring windows and appropriate sensor readings
- [x] Separate monitoring and communication
- [x] Allow for sensible switching between slideshow and monitoring modes
- [x] Allow for sensible switching into and out of AP mode

Additional bugs will be filed as necessary.

**Comment by lars-t-hansen** [comment]
The ux2 branch provides for sensible monitoring windows, allowing #33 to be fixed.

**Comment by lars-t-hansen** [comment]
Fixed with the merge from ux2.
